export interface SportsTicketServer {
  id: string;
  name: string;
  league: "KBO 야구" | "K리그 축구" | "KOVO 배구" | "KBL 농구" | "LCK e스포츠";
  category: "야구" | "축구" | "배구" | "농구" | "e스포츠";
  ticketingPlatform: "티켓링크" | "인터파크" | "예스24" | "구단 공식홈" | "KOVO 통합티켓(KOVO)" | "KBL 통합티켓(KBL)";
  domain: string;
  bookingUrl: string;
  openRule: string; // e.g. "경기일 7일 전 11:00 오픈"
  homeStadium: string;
}

export const KOREAN_SPORTS_SERVERS: SportsTicketServer[] = [
  // KBO 프로야구 (10개 구단)
  {
    id: "lg-twins",
    name: "LG 트윈스",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/baseball/63",
    openRule: "경기 7일 전 11:00 선예매 / 14:00 일반오픈",
    homeStadium: "서울 잠실야구장",
  },
  {
    id: "kia-tigers",
    name: "KIA 타이거즈",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/baseball/62",
    openRule: "경기 7일 전 11:00 일반오픈",
    homeStadium: "광주-기아 챔피언스 필드",
  },
  {
    id: "samsung-lions",
    name: "삼성 라이온즈",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/baseball/57",
    openRule: "경기 7일 전 11:00 일반오픈",
    homeStadium: "대구 삼성 라이온즈 파크",
  },
  {
    id: "kt-wiz",
    name: "kt wiz",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/baseball/64",
    openRule: "경기 7일 전 14:00 일반오픈",
    homeStadium: "수원 KT 위즈 파크",
  },
  {
    id: "ssg-landers",
    name: "SSG 랜더스",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "인터파크",
    domain: "ticket.interpark.com",
    bookingUrl: "https://ticket.interpark.com",
    openRule: "경기 4~7일 전 11:00 멤버십 / 14:00 일반예매",
    homeStadium: "인천 SSG 랜더스필드",
  },
  {
    id: "hanwha-eagles",
    name: "한화 이글스",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/baseball/65",
    openRule: "경기 7일 전 11:00 오픈",
    homeStadium: "한화생명 이글스파크",
  },
  {
    id: "lotte-giants",
    name: "롯데 자이언츠",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "구단 공식홈",
    domain: "giantsclub.com",
    bookingUrl: "https://www.giantsclub.com",
    openRule: "경기 7일 전 14:00 선예매 / 10:00 일반예매",
    homeStadium: "부산 사직야구장",
  },
  {
    id: "doosan-bears",
    name: "두산 베어스",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "인터파크",
    domain: "ticket.interpark.com",
    bookingUrl: "https://ticket.interpark.com",
    openRule: "경기 7일 전 10:00 베어스클럽 / 11:00 일반예매",
    homeStadium: "서울 잠실야구장",
  },
  {
    id: "nc-dinos",
    name: "NC 다이노스",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "구단 공식홈",
    domain: "ncdinos.com",
    bookingUrl: "https://www.ncdinos.com",
    openRule: "경기 7일 전 11:00 오픈",
    homeStadium: "창원 NC파크",
  },
  {
    id: "kiwoom-heroes",
    name: "키움 히어로즈",
    league: "KBO 야구",
    category: "야구",
    ticketingPlatform: "인터파크",
    domain: "ticket.interpark.com",
    bookingUrl: "https://ticket.interpark.com",
    openRule: "경기 7일 전 14:00 일반오픈",
    homeStadium: "서울 고척스카이돔",
  },

  // K리그 프로축구 주요 구단
  {
    id: "fc-seoul",
    name: "FC 서울",
    league: "K리그 축구",
    category: "축구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/football/77",
    openRule: "경기 5일 전 18:00 플러스멤버 / 경기 3일 전 일반",
    homeStadium: "서울월드컵경기장",
  },
  {
    id: "ulsan-hd",
    name: "울산 HD FC",
    league: "K리그 축구",
    category: "축구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/football/66",
    openRule: "경기 5일 전 12:00 멤버십 / 경기 3일 전 일반",
    homeStadium: "울산 문수축구경기장",
  },
  {
    id: "jeonbuk-hyundai",
    name: "전북 현대 모터스",
    league: "K리그 축구",
    category: "축구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/football/78",
    openRule: "경기 5일 전 12:00 선예매 / 17:00 일반오픈",
    homeStadium: "전주월드컵경기장",
  },
  {
    id: "pohang-steelers",
    name: "포항 스틸러스",
    league: "K리그 축구",
    category: "축구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/football/67",
    openRule: "경기 5일 전 11:00 오픈",
    homeStadium: "포항 스틸야드",
  },
  {
    id: "daegu-fc",
    name: "대구 FC",
    league: "K리그 축구",
    category: "축구",
    ticketingPlatform: "티켓링크",
    domain: "ticketlink.co.kr",
    bookingUrl: "http://www.ticketlink.co.kr/sports/football/84",
    openRule: "경기 7일 전 14:00 엔젤클럽 / 경기 5일 전 일반",
    homeStadium: "DGB대구은행파크",
  },
  {
    id: "suwon-samsung",
    name: "수원 삼성 블루윙즈",
    league: "K리그 축구",
    category: "축구",
    ticketingPlatform: "인터파크",
    domain: "ticket.interpark.com",
    bookingUrl: "https://ticket.interpark.com",
    openRule: "경기 5일 전 14:00 블루패스 / 경기 3일 전 일반",
    homeStadium: "수원월드컵경기장",
  },

  // KOVO 프로배구
  {
    id: "heungkuk-pinkspiders",
    name: "흥국생명 핑크스파이더스",
    league: "KOVO 배구",
    category: "배구",
    ticketingPlatform: "KOVO 통합티켓(KOVO)",
    domain: "kovo.co.kr",
    bookingUrl: "https://www.kovo.co.kr",
    openRule: "경기 5일 전 14:00 선예매 / 15:00 일반예매",
    homeStadium: "인천 삼산월드체육관",
  },
  {
    id: "hyundai-skywalkers",
    name: "현대캐피탈 스카이워커스",
    league: "KOVO 배구",
    category: "배구",
    ticketingPlatform: "KOVO 통합티켓(KOVO)",
    domain: "kovo.co.kr",
    bookingUrl: "https://www.kovo.co.kr",
    openRule: "경기 5일 전 12:00 멤버십 / 14:00 일반예매",
    homeStadium: "천안 유관순체육관",
  },
  {
    id: "korean-air-jumbos",
    name: "대한항공 점보스",
    league: "KOVO 배구",
    category: "배구",
    ticketingPlatform: "KOVO 통합티켓(KOVO)",
    domain: "kovo.co.kr",
    bookingUrl: "https://www.kovo.co.kr",
    openRule: "경기 5일 전 13:00 오픈",
    homeStadium: "인천 계양체육관",
  },
  {
    id: "hyundai-hillstate",
    name: "현대건설 힐스테이트",
    league: "KOVO 배구",
    category: "배구",
    ticketingPlatform: "KOVO 통합티켓(KOVO)",
    domain: "kovo.co.kr",
    bookingUrl: "https://www.kovo.co.kr",
    openRule: "경기 5일 전 14:00 오픈",
    homeStadium: "수원실내체육관",
  },

  // KBL 프로농구
  {
    id: "kcc-egis",
    name: "부산 KCC 이지스",
    league: "KBL 농구",
    category: "농구",
    ticketingPlatform: "KBL 통합티켓(KBL)",
    domain: "kbl.or.kr",
    bookingUrl: "https://www.kbl.or.kr",
    openRule: "경기 7일 전 11:00 오픈",
    homeStadium: "부산 사직실내체육관",
  },
  {
    id: "sk-knights",
    name: "서울 SK 나이츠",
    league: "KBL 농구",
    category: "농구",
    ticketingPlatform: "KBL 통합티켓(KBL)",
    domain: "kbl.or.kr",
    bookingUrl: "https://www.kbl.or.kr",
    openRule: "경기 7일 전 14:00 오픈",
    homeStadium: "서울 잠실학생체육관",
  },
  {
    id: "wonju-db",
    name: "원주 DB 프로미",
    league: "KBL 농구",
    category: "농구",
    ticketingPlatform: "KBL 통합티켓(KBL)",
    domain: "kbl.or.kr",
    bookingUrl: "https://www.kbl.or.kr",
    openRule: "경기 7일 전 11:00 오픈",
    homeStadium: "원주종합체육관",
  },

  // LCK e스포츠
  {
    id: "lck-lol-park",
    name: "LCK e스포츠 (LOL PARK)",
    league: "LCK e스포츠",
    category: "e스포츠",
    ticketingPlatform: "인터파크",
    domain: "ticket.interpark.com",
    bookingUrl: "https://ticket.interpark.com",
    openRule: "경기 48시간 전 17:00 정각 1차 / 19:30 정각 2차 오픈",
    homeStadium: "서울 종로 롤파크(LOL PARK)",
  },
];
