export interface UniversityCourseServer {
  id: string;
  name: string;
  shortName: string;
  domain: string;
  courseUrl: string;
  region: "서울" | "수도권" | "지방거점" | "특성화";
  openTimeDesc: string; // e.g. "매학기 10:00 오픈"
}

export const KOREAN_UNIVERSITIES: UniversityCourseServer[] = [
  // 서울권 주요 대학
  {
    id: "snu",
    name: "서울대학교",
    shortName: "서울대",
    domain: "sugang.snu.ac.kr",
    courseUrl: "https://sugang.snu.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 08:30 / 10:00 오픈",
  },
  {
    id: "korea",
    name: "고려대학교",
    shortName: "고려대",
    domain: "sugang.korea.ac.kr",
    courseUrl: "https://sugang.korea.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "yonsei",
    name: "연세대학교",
    shortName: "연세대",
    domain: "portal.yonsei.ac.kr",
    courseUrl: "https://portal.yonsei.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 마일리지/10:00 오픈",
  },
  {
    id: "skku",
    name: "성균관대학교",
    shortName: "성균관대",
    domain: "sugang.skku.edu",
    courseUrl: "https://sugang.skku.edu",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "hanyang",
    name: "한양대학교",
    shortName: "한양대",
    domain: "portal.hanyang.ac.kr",
    courseUrl: "https://portal.hanyang.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 11:00 오픈",
  },
  {
    id: "cau",
    name: "중앙대학교",
    shortName: "중앙대",
    domain: "sugang.cau.ac.kr",
    courseUrl: "https://sugang.cau.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "khu",
    name: "경희대학교",
    shortName: "경희대",
    domain: "sugang.khu.ac.kr",
    courseUrl: "https://sugang.khu.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:30 오픈",
  },
  {
    id: "hufs",
    name: "한국외국어대학교",
    shortName: "한국외대",
    domain: "wis.hufs.ac.kr",
    courseUrl: "https://wis.hufs.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "uos",
    name: "서울시립대학교",
    shortName: "서울시립대",
    domain: "sugang.uos.ac.kr",
    courseUrl: "https://sugang.uos.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "ewha",
    name: "이화여자대학교",
    shortName: "이화여대",
    domain: "sugang.ewha.ac.kr",
    courseUrl: "https://sugang.ewha.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "sogang",
    name: "서강대학교",
    shortName: "서강대",
    domain: "sugang.sogang.ac.kr",
    courseUrl: "https://sugang.sogang.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 / 17:00 오픈",
  },
  {
    id: "konkuk",
    name: "건국대학교",
    shortName: "건국대",
    domain: "sugang.konkuk.ac.kr",
    courseUrl: "https://sugang.konkuk.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 09:30 오픈",
  },
  {
    id: "dongguk",
    name: "동국대학교",
    shortName: "동국대",
    domain: "sugang.dongguk.edu",
    courseUrl: "https://sugang.dongguk.edu",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "hongik",
    name: "홍익대학교",
    shortName: "홍익대",
    domain: "sugang.hongik.ac.kr",
    courseUrl: "https://sugang.hongik.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "kookmin",
    name: "국민대학교",
    shortName: "국민대",
    domain: "sugang.kookmin.ac.kr",
    courseUrl: "https://sugang.kookmin.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "soongsil",
    name: "숭실대학교",
    shortName: "숭실대",
    domain: "sugang.ssu.ac.kr",
    courseUrl: "https://sugang.ssu.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "sejong",
    name: "세종대학교",
    shortName: "세종대",
    domain: "portal.sejong.ac.kr",
    courseUrl: "https://portal.sejong.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "dankook",
    name: "단국대학교",
    shortName: "단국대",
    domain: "sugang.dankook.ac.kr",
    courseUrl: "https://sugang.dankook.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "ajou",
    name: "아주대학교",
    shortName: "아주대",
    domain: "sugang.ajou.ac.kr",
    courseUrl: "https://sugang.ajou.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "inha",
    name: "인하대학교",
    shortName: "인하대",
    domain: "sugang.inha.ac.kr",
    courseUrl: "https://sugang.inha.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 09:00 / 10:00 오픈",
  },
  {
    id: "erica",
    name: "한양대 ERICA",
    shortName: "에리카",
    domain: "portal.hanyang.ac.kr",
    courseUrl: "https://portal.hanyang.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 11:00 오픈",
  },
  {
    id: "catholic",
    name: "가톨릭대학교",
    shortName: "가톨릭대",
    domain: "sugang.catholic.ac.kr",
    courseUrl: "https://sugang.catholic.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "gachon",
    name: "가천대학교",
    shortName: "가천대",
    domain: "sugang.gachon.ac.kr",
    courseUrl: "https://sugang.gachon.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "mju",
    name: "명지대학교",
    shortName: "명지대",
    domain: "sugang.mju.ac.kr",
    courseUrl: "https://sugang.mju.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "sangmyung",
    name: "상명대학교",
    shortName: "상명대",
    domain: "sugang.smu.ac.kr",
    courseUrl: "https://sugang.smu.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "hansung",
    name: "한성대학교",
    shortName: "한성대",
    domain: "info.hansung.ac.kr",
    courseUrl: "https://info.hansung.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "seokyeong",
    name: "서경대학교",
    shortName: "서경대",
    domain: "sugang.skuniv.ac.kr",
    courseUrl: "https://sugang.skuniv.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "samook",
    name: "삼육대학교",
    shortName: "삼육대",
    domain: "sugang.syu.ac.kr",
    courseUrl: "https://sugang.syu.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "sungshin",
    name: "성신여자대학교",
    shortName: "성신여대",
    domain: "sugang.sungshin.ac.kr",
    courseUrl: "https://sugang.sungshin.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "sookmyung",
    name: "숙명여자대학교",
    shortName: "숙명여대",
    domain: "sugang.sookmyung.ac.kr",
    courseUrl: "https://sugang.sookmyung.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "dongduk",
    name: "동덕여자대학교",
    shortName: "동덕여대",
    domain: "sugang.dongduk.ac.kr",
    courseUrl: "https://sugang.dongduk.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "seoultech",
    name: "서울과학기술대학교",
    shortName: "서울과기대",
    domain: "sugang.seoultech.ac.kr",
    courseUrl: "https://sugang.seoultech.ac.kr",
    region: "서울",
    openTimeDesc: "학기별 09:30 오픈",
  },
  {
    id: "kaist",
    name: "KAIST (한국과학기술원)",
    shortName: "카이스트",
    domain: "portal.kaist.ac.kr",
    courseUrl: "https://portal.kaist.ac.kr",
    region: "특성화",
    openTimeDesc: "학기별 12:30 오픈",
  },
  {
    id: "postech",
    name: "포항공과대학교",
    shortName: "포스텍",
    domain: "povis.postech.ac.kr",
    courseUrl: "https://povis.postech.ac.kr",
    region: "특성화",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "gist",
    name: "GIST (광주과학기술원)",
    shortName: "지스트",
    domain: "zeus.gist.ac.kr",
    courseUrl: "https://zeus.gist.ac.kr",
    region: "특성화",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "dgist",
    name: "DGIST (대구경북과학기술원)",
    shortName: "디지스트",
    domain: "portal.dgist.ac.kr",
    courseUrl: "https://portal.dgist.ac.kr",
    region: "특성화",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "unist",
    name: "UNIST (울산과학기술원)",
    shortName: "유니스트",
    domain: "portal.unist.ac.kr",
    courseUrl: "https://portal.unist.ac.kr",
    region: "특성화",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "pnu",
    name: "부산대학교",
    shortName: "부산대",
    domain: "sugang.pusan.ac.kr",
    courseUrl: "https://sugang.pusan.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 08:30 / 10:00 오픈",
  },
  {
    id: "knu",
    name: "경북대학교",
    shortName: "경북대",
    domain: "sugang.knu.ac.kr",
    courseUrl: "https://sugang.knu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "cnu",
    name: "전남대학교",
    shortName: "전남대",
    domain: "sugang.jnu.ac.kr",
    courseUrl: "https://sugang.jnu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 09:30 오픈",
  },
  {
    id: "chungnam",
    name: "충남대학교",
    shortName: "충남대",
    domain: "sugang.cnu.ac.kr",
    courseUrl: "https://sugang.cnu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "chungbuk",
    name: "충북대학교",
    shortName: "충북대",
    domain: "sugang.cbnu.ac.kr",
    courseUrl: "https://sugang.cbnu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "jbnu",
    name: "전북대학교",
    shortName: "전북대",
    domain: "all.jbnu.ac.kr",
    courseUrl: "https://all.jbnu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "kangwon",
    name: "강원대학교",
    shortName: "강원대",
    domain: "sugang.kangwon.ac.kr",
    courseUrl: "https://sugang.kangwon.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "gnu",
    name: "경상국립대학교",
    shortName: "경상국립대",
    domain: "sugang.gnu.ac.kr",
    courseUrl: "https://sugang.gnu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "jejunu",
    name: "제주대학교",
    shortName: "제주대",
    domain: "sugang.jejunu.ac.kr",
    courseUrl: "https://sugang.jejunu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "knue",
    name: "한국교원대학교",
    shortName: "교원대",
    domain: "sugang.knue.ac.kr",
    courseUrl: "https://sugang.knue.ac.kr",
    region: "특성화",
    openTimeDesc: "학기별 09:00 오픈",
  },
  {
    id: "inha-tech",
    name: "인하공업전문대학",
    shortName: "인하공전",
    domain: "sugang.itc.ac.kr",
    courseUrl: "https://sugang.itc.ac.kr",
    region: "수도권",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "hallym",
    name: "한림대학교",
    shortName: "한림대",
    domain: "sugang.hallym.ac.kr",
    courseUrl: "https://sugang.hallym.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "wonkwang",
    name: "원광대학교",
    shortName: "원광대",
    domain: "sugang.wku.ac.kr",
    courseUrl: "https://sugang.wku.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 09:30 오픈",
  },
  {
    id: "chosun",
    name: "조선대학교",
    shortName: "조선대",
    domain: "sugang.chosun.ac.kr",
    courseUrl: "https://sugang.chosun.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "yeungnam",
    name: "영남대학교",
    shortName: "영남대",
    domain: "sugang.yu.ac.kr",
    courseUrl: "https://sugang.yu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "keimyung",
    name: "계명대학교",
    shortName: "계명대",
    domain: "sugang.kmu.ac.kr",
    courseUrl: "https://sugang.kmu.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
  {
    id: "donga",
    name: "동아대학교",
    shortName: "동아대",
    domain: "sugang.donga.ac.kr",
    courseUrl: "https://sugang.donga.ac.kr",
    region: "지방거점",
    openTimeDesc: "학기별 10:00 오픈",
  },
];
