import { NormalizedEvent } from "./types";

// Isolated seed fixtures strictly kept away from runtime scraper implementations
export const FIXTURE_EVENTS: NormalizedEvent[] = [
  {
    id: "evt-iu-worldtour-2026",
    slug: "iu-worldtour-seoul",
    title: "아이유 월드투어 서울",
    category: "concert",
    platform: "interpark",
    platformName: "NOL 티켓",
    hostDomain: "ticket.interpark.com",
    hostSlug: "interpark",
    sourceUrl: "https://ticket.interpark.com/Goods/GoodsInfo.asp?GoodsCode=26010001",
    officialUrl: "https://edam.ent.com/iu",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80",
    openAt: "2026-10-02T20:00:00+09:00", // 20:00 KST
    venue: "KSPO DOME (올림픽체조경기장)",
    status: "SCHEDULED",
    confidenceScore: 0.98,
    sourceType: "FIXTURE",
    waitingCount: 12382,
    tags: ["선예매", "아이유", "체조경기장", "전석지정"],
  },
  {
    id: "evt-seventeen-fanmeet-2026",
    slug: "seventeen-fanmeeting",
    title: "세븐틴 캐럿 팬미팅",
    category: "concert",
    platform: "yes24",
    platformName: "예스24 티켓",
    hostDomain: "ticket.yes24.com",
    hostSlug: "yes24",
    sourceUrl: "http://ticket.yes24.com/Special/202601",
    officialUrl: "https://pledis.co.kr/seventeen",
    imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80",
    openAt: "2026-10-02T20:00:00+09:00", // 20:00 KST
    venue: "고척스카이돔",
    status: "SCHEDULED",
    confidenceScore: 0.95,
    sourceType: "FIXTURE",
    waitingCount: 8194,
    tags: ["팬클럽선예매", "세븐틴", "고척돔"],
  },
  {
    id: "evt-suneung-apply-2026",
    slug: "2026-suneung-application",
    title: "2026 수능 원서접수",
    category: "university",
    platform: "custom",
    platformName: "한국교육과정평가원",
    hostDomain: "kice.re.kr",
    hostSlug: "kice",
    sourceUrl: "https://www.kice.re.kr",
    imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80",
    openAt: "2026-10-02T19:00:00+09:00", // 19:00 KST
    venue: "전국 지정 접수처 및 온라인",
    status: "SCHEDULED",
    confidenceScore: 0.99,
    sourceType: "FIXTURE",
    waitingCount: 3122,
    tags: ["수능", "원서접수", "평가원"],
  },
  {
    id: "evt-seongsu-popup-2026",
    slug: "seongsu-popup-store",
    title: "성수 플래그십 팝업스토어 예약",
    category: "popup",
    platform: "naver",
    platformName: "네이버 예약",
    hostDomain: "booking.naver.com",
    hostSlug: "naver-booking",
    sourceUrl: "https://booking.naver.com/booking/12/bizes/9999",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80",
    openAt: "2026-10-02T19:30:00+09:00", // 19:30 KST
    venue: "성수동 서울숲 카페거리",
    status: "SCHEDULED",
    confidenceScore: 0.92,
    sourceType: "FIXTURE",
    waitingCount: 2412,
    tags: ["성수", "팝업", "네이버예약"],
  },
  {
    id: "evt-worldcup-qualifier-2026",
    slug: "worldcup-qualifier-korea",
    title: "월드컵 최종예선 대한민국 vs 일본",
    category: "sports",
    platform: "ticketlink",
    platformName: "티켓링크",
    hostDomain: "ticketlink.co.kr",
    hostSlug: "ticketlink",
    sourceUrl: "https://www.ticketlink.co.kr/sports/football",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80",
    openAt: "2026-10-03T20:00:00+09:00", // Tomorrow 20:00 KST
    venue: "서울월드컵경기장 (상암)",
    status: "SCHEDULED",
    confidenceScore: 0.94,
    sourceType: "FIXTURE",
    waitingCount: 6540,
    tags: ["축구", "A매치", "국가대표", "상암"],
  },
  {
    id: "evt-yonsei-course-reg-2026",
    slug: "yonsei-course-registration",
    title: "연세대학교 2학기 희망과목 담기",
    category: "university",
    platform: "custom",
    platformName: "연세포탈서비스",
    hostDomain: "portal.yonsei.ac.kr",
    hostSlug: "yonsei-portal",
    sourceUrl: "https://portal.yonsei.ac.kr",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80",
    openAt: "2026-10-04T10:00:00+09:00", // Oct 4 10:00 KST
    venue: "학사정보시스템",
    status: "SCHEDULED",
    confidenceScore: 0.96,
    sourceType: "FIXTURE",
    waitingCount: 4210,
    tags: ["연세대", "수강신청", "희망과목"],
  },
];

export const POPULAR_SERVERS = [
  { rank: 1, name: "NOL 티켓", domain: "ticket.interpark.com", slug: "interpark", viewers: 12382, tag: "NOL" },
  { rank: 2, name: "예스24", domain: "ticket.yes24.com", slug: "yes24", viewers: 8194, tag: "YES24" },
  { rank: 3, name: "티켓링크", domain: "ticketlink.co.kr", slug: "ticketlink", viewers: 3122, tag: "PAYCO" },
  { rank: 4, name: "멜론티켓", domain: "ticket.melon.com", slug: "melon", viewers: 2841, tag: "MELON" },
  { rank: 5, name: "네이버 예약", domain: "booking.naver.com", slug: "naver-booking", viewers: 2172, tag: "NAVER" },
  { rank: 6, name: "캐치테이블", domain: "catchtable.co.kr", slug: "catchtable", viewers: 1845, tag: "CATCH" },
  { rank: 7, name: "무신사", domain: "musinsa.com", slug: "musinsa", viewers: 1620, tag: "DROP" },
];

export const SURGING_EVENTS = [
  { rank: 1, title: "아이유 월드투어", surgeRate: "+842%", slug: "iu-worldtour-seoul" },
  { rank: 2, title: "2026 수능 원서접수", surgeRate: "+382%", slug: "2026-suneung-application" },
  { rank: 3, title: "세븐틴 팬미팅", surgeRate: "+281%", slug: "seventeen-fanmeeting" },
  { rank: 4, title: "성수 팝업스토어", surgeRate: "+122%", slug: "seongsu-popup-store" },
  { rank: 5, title: "월드컵 티켓팅", surgeRate: "+98%", slug: "worldcup-qualifier-korea" },
];
